# Generated by Django 5.1.7 on 2025-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zagadki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numer", models.IntegerField(unique=True)),
                ("kod", models.CharField(max_length=255)),
            ],
        ),
    ]
